listening-port=3478
fingerprint
use-auth-secret
static-auth-secret=change-this-turn-secret
realm=nunuterapi.com
server-name=nunuterapi-turn
lt-cred-mech
no-multicast-peers
no-loopback-peers
external-ip=PUBLIC_IP
min-port=49152
max-port=65535
verbose
